services:
  node:
    build: ./
    image: doty/eleventy
    network_mode: host
    container_name: doty
    working_dir: /home/node/app
    volumes:
     - ./_dist:/home/node/app/_dist
     - ./src:/home/node/app/src
